server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spring_security_template}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:spring_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:spring_password}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.sql.init.platform=${SPRING_SQL_INIT_PLATFORM:postgresql}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

token.signing.key=${TOKEN_SIGNING_KEY:bXktdmVyeS1zZWNyZXQta2V5LTEyMzQ1Njc4OTAxMjM0NTY=}
